#!/usr/bin/env -S bun run

/// <reference types="bun-types" />

// Regenerate src/content/README.md from the content collections.
//
// Run by the `content-readme` pre-commit hook (and `bun run content`). It
// owns the file end to end: render the index, then format with oxfmt so the
// output is canonical and coexists with the treefmt hook without a reformat
// loop.

const CONTENT_DIR = "src/content";
const README = `${CONTENT_DIR}/README.md`;

type Entry = { id: string; data: Record<string, unknown> };
type Column = { header: string; align?: "right"; value: (e: Entry) => string };

const str = (v: unknown): string => (Array.isArray(v) ? v.join(", ") : (v ?? "").toString());

// projects and kap92 share the same number/id/name shape. The id is the
// filename, not a frontmatter field.
const numberId: Column[] = [
  { header: "number", align: "right", value: (e) => str(e.data.number) },
  { header: "id", value: (e) => `\`${str(e.id)}\`` },
  { header: "name", value: (e) => str(e.data.name) },
];
const byNumber = (a: Entry, b: Entry): number => Number(a.data.number) - Number(b.data.number);

const COLLECTIONS: {
  name: string;
  description: string;
  columns: Column[];
  sort: (a: Entry, b: Entry) => number;
}[] = [
  {
    name: "projects",
    description:
      "Artpolis commissioned new builds, listed at <https://www.pref.kumamoto.jp/soshiki/115/83273.html>.",
    columns: numberId,
    sort: byNumber,
  },
  {
    name: "kap92",
    description:
      "KAP'92 selected existing buildings, listed at <https://www.pref.kumamoto.jp/soshiki/115/4477.html>.",
    columns: numberId,
    sort: byNumber,
  },
  {
    name: "status",
    description: "Visit records, one file per visit (filename is the ISO datetime).",
    columns: [
      { header: "datetime", value: (e) => `\`${e.id}\`` },
      {
        header: "entry",
        value: (e) => {
          const id = e.data.project ?? e.data.kap92;
          return id ? `\`${str(id)}\`` : "";
        },
      },
    ],
    sort: (a, b) => b.id.localeCompare(a.id),
  },
];

async function readEntries(name: string): Promise<Entry[]> {
  const dir = `${CONTENT_DIR}/${name}`;
  const entries: Entry[] = [];
  for (const file of new Bun.Glob("*.md").scanSync(dir)) {
    const raw = await Bun.file(`${dir}/${file}`).text();
    const block = raw.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";
    entries.push({
      id: file.slice(0, -3),
      data: (Bun.YAML.parse(block) as Record<string, unknown> | null) ?? {},
    });
  }
  return entries;
}

// Render a GitHub Markdown table. Cells aren't padded here; oxfmt aligns them.
function renderTable(columns: Column[], entries: Entry[]): string {
  const row = (cells: string[]) => `| ${cells.join(" | ")} |`;
  return [
    row(columns.map((c) => c.header)),
    row(columns.map((c) => (c.align === "right" ? "---:" : "---"))),
    ...entries.map((e) => row(columns.map((c) => c.value(e)))),
  ].join("\n");
}

async function renderReadme(): Promise<string> {
  const sections: string[] = [];
  for (const c of COLLECTIONS) {
    const parts = [`## \`${c.name}/\``, "", c.description];
    const entries = (await readEntries(c.name)).sort(c.sort);
    if (entries.length > 0) parts.push("", renderTable(c.columns, entries));
    sections.push(parts.join("\n"));
  }
  return [
    "# content",
    "",
    "<!-- AUTO-GENERATED by scripts/content-readme.ts. Do not edit by hand. -->",
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");
}

await Bun.write(README, await renderReadme());
await Bun.$`oxfmt ${README}`.quiet().nothrow();

export {};
